services:
  dev:
    build: .
    container_name: c-dev

    volumes:
      - .:/workspace

    working_dir: /workspace

    mem_limit: 4g
    environment:
      - PYTHONUNBUFFERED=1

    stdin_open: true
    tty: true
