services:
  main:
    container_name: simulation_main
    stdin_open: true
    tty: true
    build: .
    volumes:
      - .:/finds
    working_dir: /finds
    command: python3 -m finds.main

    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G