services:
  base: &base
    build: .
    volumes:
      - .:/finds
    working_dir: /finds
    mem_limit: 4g
    environment:
      - PYTHONUNBUFFERED=1
    stdin_open: true
    tty: true

  main:
    <<: *base
    command: python3 -m finds.main

  validation:
    <<: *base
    command: python3 -m finds.validation

  docs:
    <<: *base
    working_dir: /finds/docs
    command: make all

  repl:
    <<: *base
    command: |
      python3 -i <<'EOF'
      from finds import *;
      from finds.fish import *;
      from finds.calculations import *;
      from finds.simulation import *;
      from test.common import *;
      print("FInDS REPL loaded");
      EOF
