import time
from datetime import datetime
from pathlib import Path

from numba import njit
from numpy.typing import NDArray

from .calculations import calculate_system_derivative
from .fish import normalize_orientation_vectors
from .io import (close_filestream, init_output_filestream,
                 serialize_to_file)
from .constants import DATA_FILE_NAME

@njit
def calculate_update_rk4(
        system: NDArray,
        time_step: float,
        use_barnes_hut: bool=False,
        bh_ratio: float=None) -> NDArray:
    r"""
    Computes the updated state of the school after the next time step
    using fourth-order Runge-Kutta.

    :param system: The system/school of fish to be updated by one
      :math:`\delta t`.
    :type  system: NDArray

    :param time_step: The differential time-step for the calculation,
      :math:`\delta t`
    :type  time_step: float

    :param use_barnes_hut: Whether or not to simplify with Barnes-Hut
      approximation.
    :type  use_barnes_hut: bool

    :param bh_ratio: The Barnes-Hut Ratio
    :type  bh_ratio: float

    :returns: The updated state after one time-step.
    :rtype: NDArray

    We define :math:`f(\mathbf{X})` as
    :py:func:`src.calculations.calculate_system_derivative`
    and :math:`\mathbf{X}_0` as :code:`system`. Using a time step
    :math:`\delta t` and subsequent half-step :math:`\delta t_{1/2} =
    \delta t/2`, then, the following calculations are used to produce the
    system's updated state at the next time step,
    :math:`\mathbf{X}_{\delta t}`.

    .. math::
        :nowrap:

        \begin{align}
        \dot{\mathbf{X}}_1 &= f(\mathbf{X}_0)  \\
        \dot{\mathbf{X}}_2 &= f(\mathbf{X}_0 + \dot{\mathbf{X}}_1
          \delta t_{1/2}) \\
        \dot{\mathbf{X}}_3 &= f(\mathbf{X}_0 + \dot{\mathbf{X}}_2
          \delta t_{1/2}) \\
        \dot{\mathbf{X}}_4 &= f(\mathbf{X}_0 + \dot{\mathbf{X}}_3 \delta t)
        \end{align}

    Then, the final derivative :math:`\dot{\mathbf{X}}` is computed as

    .. math::
        \dot{\mathbf{X}} \approx \frac{\dot{\mathbf{X}}_1 + 2
        \dot{\mathbf{X}}_2 + 2 \dot{\mathbf{X}}_3 + \dot{\mathbf{X}}_4}{6}

    And the resulting updated system is computed as

    .. math::
        \mathbf{X}_{\delta t} = \mathbf{X}_0 + \dot{\mathbf{X}} \delta t

    Before returning, the orientation vectors need to be renormalized, and
    this is done through
    :py:func:`src.calculations.normalize_orientation_vectors`.
    """
    X0 = system
    g  = calculate_system_derivative
    f  = lambda X: g(X, use_barnes_hut, bh_ratio)
    n  = normalize_orientation_vectors
    dt = time_step

    # normalize the orientation vectors at each step to prevent issues
    k1 = f(n(X0))
    k2 = f(n(X0 + k1 * dt / 2))
    k3 = f(n(X0 + k2 * dt / 2))
    k4 = f(n(X0 + k3 * dt))

    k = (k1 + 2 * k2 + 2 * k3 + k4) / 6
    Xt = n(X0 + k * dt)

    return Xt


def perform_simulation(
        initial_state: NDArray,
        time_step: float,
        end_time: float,
        use_barnes_hut: bool = False,
        bh_ratio: float = None,
        print_to_file: bool = True,
        debug_print: bool = True) -> Path:
    r"""
    Performs the simulation using Runge-Kutta fourth-order, then optionally
    saves the path information for each state to a datafile and produces an
    animation.

    :param initial_state: The initial system state, :math:`\mathbf{X}(t=0)`.
    :type  initial_state: NDArray

    :param time_step: :math:`\delta t`
    :type  time_step: float

    :param end_time: The time to stop the simulation at.
    :type  end_time: float

    :param use_barnes_hut: Whether or not to simplify with Barnes-Hut
      approximation.
    :type  use_barnes_hut: bool

    :param bh_ratio: The Barnes-Hut Ratio
    :type  bh_ratio: float

    :param print_to_file: Whether or not to save the path generated from the
      simulation to an autogenerated CSV file, located at
      `output/test-(timestamp)/path.csv`.
    :type  print_to_file: bool

    :returns: The path of the testing output directory.
    :rtype: Path
    """
    system = initial_state.copy()
    irl_start_time = time.time()

    # generate a new file at output/test-{timestamp}/path.csv
    timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")

    output_dir = Path(f"output/test-{timestamp}")
    if print_to_file:
        output_dir.mkdir(parents=True, exist_ok=True)

    output_filename = output_dir / DATA_FILE_NAME
    output_io = init_output_filestream(output_filename, system.shape[0])

    if print_to_file:
        print(f'Writing data to {output_filename}')
        serialize_to_file(system, 0, output_io)

    # saving some iteration markers for debugging
    total_iterations = int(end_time / time_step)
    interval = max(total_iterations // 10, 1)

    # the actual iteration stepper
    for simulation_index in range(total_iterations):

        # debug printing
        if simulation_index % interval == 0:
            fraction = simulation_index / float(total_iterations)
            print(f'{fraction * 100:.0f}% - '+
                  f'Iteration {simulation_index}/{total_iterations}')

        # compute the next state via RK4
        system = calculate_update_rk4(
            system, time_step, use_barnes_hut, bh_ratio)

        # update the iteration indices
        simulation_index += 1
        simulation_time = simulation_index * time_step

        # save to the file
        serialize_to_file(system, simulation_time, output_io)

    # close filestream
    close_filestream(output_io)

    if debug_print:
        print('100% - Completed.')

    irl_end_time = time.time()

    # compute and print the elapsed time
    if debug_print:
        elapsed = irl_end_time - irl_start_time

        hours, rem = divmod(elapsed, 3600)
        minutes, rem = divmod(rem, 60)
        seconds = int(rem)
        milliseconds = int((rem - seconds) * 1000)

        print(f"Executed in {hours}h "+
              f"{minutes}m "+
              f"{seconds}s "+
              f"{milliseconds:.1f}ms")

    return output_dir
