name: Build and Deploy Documentation

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  documentation:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build Docker Image
        run: make build

      - name: Build Documentation
        run: make docs

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/html

  deploy:
    needs: documentation
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
